{% set name = "zarr" %}
{% set version = "2.10.0" %}
{% set sha256 = "8ca8e505cadb4f7f97aab4e4193bb302b6338bf54593c98fe7581bf574ed864c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools >=38.6.0
    - setuptools_scm >1.5.4
  run:
    - python >=3.5
    - asciitree
    - numpy >=1.7
    - fasteners
    - numcodecs >=0.6.4

test:
  requires:
    - pytest
    # Needs `pkg_resources` in the tests
    # xref: https://github.com/zarr-developers/zarr-python/pull/813
    - setuptools
  imports:
    - zarr
  commands:
    - pytest -v --pyargs zarr

about:
  home: https://github.com/zarr-developers/zarr
  license: MIT
  license_file: LICENSE
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python.

extra:
  recipe-maintainers:
    - alimanfoo
    - Carreau
    - grlee77
    - jakirkham
    - joshmoore
    - jrbourbeau
