{% set name = "zarr" %}
{% set version = "2.18.0" %}
{% set sha256 = "c3b7d2c85b8a42b0ad0ad268a36fb6886ca852098358c125c6b126a417e0a598" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=64.0.0
    - setuptools-scm >1.5.4
  run:
    - python >=3.9
    - asciitree
    - numpy >=1.23
    - fasteners
    - numcodecs >=0.10.0
  run_constrained:
    # Add `zarr[jupyter]` dependencies to `run_constrained`.
    # That way the correct versions of these will be installed
    # when these packages are requested. Otherwise they are not
    # installed.
    - notebook
    - ipytree >=0.2.2
    - ipywidgets >=8.0.0

test:
  requires:
    - pip
    - pytest
    # Needs `packaging` in the tests
    # xref: https://github.com/zarr-developers/zarr-python/pull/1450
    - packaging
  imports:
    - zarr
  commands:
    - pip check
    - pytest -v --pyargs zarr

about:
  home: https://github.com/zarr-developers/zarr-python
  license: MIT
  license_file: LICENSE.txt
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python
  doc_url: https://zarr.readthedocs.io/

extra:
  recipe-maintainers:
    - normanrz
    - martindurant
    - d-v-b
    - jakirkham
    - joshmoore
    - jhamman
    - rabernat
