{% set name = "zarr" %}
{% set version = "2.4.0" %}
{% set sha256 = "53aa21b989a47ddc5e916eaff6115b824c0864444b1c6f3aaf4f6cf9a51ed608" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  build:
    - python
    - pip
    - setuptools >=38.6.0
    - setuptools_scm >1.5.4
  host:
    - python >=3.5
  run:
    - python >=3.5
    - asciitree
    - numpy >=1.7
    - fasteners
    - numcodecs >=0.6.4

test:
  requires:
    - pytest
  imports:
    - zarr
  commands:
    - pytest -v --pyargs zarr

about:
  home: https://github.com/zarr-developers/zarr
  license: MIT
  license_file: LICENSE
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python.

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jrbourbeau
