travis:
  secure:
    BINSTAR_TOKEN: J6PCZe/t0rBhAEQYBliBkfBmVGcpnsI6D1xpSs46BSIis5L8J1/nOy05QjjkTGhiTHh+l42ytesPhDMNpC+KH5XYDQSAODnEWWZ+z7oi5Pe5ks6KxkRceZx3bFoLtBZsOIpAthJoMtyNcUqDiswl+Wu9zrWxGQ49qDF6xqrsvXGiYV701PjESQyUFPhlB5Lq46d/8RCdX83g2yBGMkJHSmYCRNFf9FKRNI8TDHXH8BmamPHh7yf9KdztuRlFtDOmuvDo8JN0Gs2xyHTvqpAu7byIS0GGRderSJZZh45k54f+hV8xXR3AZHWPpSS7b8a2ciMNserI55v+lex8Klotx2/JW1nWNRq8ljqhR/uVy7KpX1jD2EeKmWQp6h29gEsCKjc77RJykMAREUeltksoxNHCHY6Q0PF0NQPtoXAN4QRseXK5XndXba1z0H1P8PiuCj1rSdC6c5/oVzvDu58VoR86dab8ifK7yF88SOHwC/VHX6z9lr+gSAX5Oh4RX1SBqjum59xnHuCGvJppFD/ifYmXb8m0bGAf58Oc2rLsY3St1bf/ZOTW+weAxqZ4iAnq8/YYtw53ArQywjiDRnAJ4MxrDiprxxXSE4FoztMzbkMF7JV5QrJR4JGEJ9q+78TIIIjEKeA8g3lEKI9ytvcT2N+rxV7N01zL/CnfRp8uOzU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
